# Generated by Django 5.2.4 on 2025-07-24 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Etkinlik Başlığı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("location", models.CharField(max_length=255, verbose_name="Yer")),
                ("start_time", models.DateTimeField(verbose_name="Başlangıç Zamanı")),
                ("end_time", models.DateTimeField(verbose_name="Bitiş Zamanı")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="groups.group",
                        verbose_name="Grup",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizatör",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="participated_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Katılımcılar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etkinlik",
                "verbose_name_plural": "Etkinlikler",
                "ordering": ["start_time"],
            },
        ),
    ]
