# Generated by Django 5.2.4 on 2025-09-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Herkese Açık'),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Katılımcı Sınırı'),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/', verbose_name='Kapak Resmi'),
        ),
    ]
