# Generated by Django 5.2.4 on 2025-09-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL'),
        ),
    ]
