# Generated by Django 5.2.4 on 2025-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Onay Gerekli'),
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True, verbose_name='İstek Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='requests', to='events.event')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etkinlik Katılım İsteği',
                'verbose_name_plural': 'Etkinlik Katılım İstekleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventrequest',
            unique_together={('event', 'user')},
        ),
    ]
