# Generated by Django 5.2.4 on 2025-07-26 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Yeni Mesaj"),
                            ("group_invite", "Grup Daveti"),
                            ("ride_request", "Yolculuk Katılım İsteği"),
                            ("ride_update", "Yolculuk Güncellemesi"),
                            ("group_update", "Grup Güncellemesi"),
                            ("friend_request", "Arkadaşlık İsteği"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Bildirim Türü",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Nesne ID")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Zaman Damgası"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="İçerik Türü",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alıcı",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderici",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-timestamp"],
            },
        ),
    ]
