# Generated by Django 5.2.4 on 2025-07-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="İçerik Türü",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nesne ID"
            ),
        ),
    ]
