# Generated by Django 5.2.4 on 2025-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('message', 'Yeni Mesaj'),
                    ('group_invite', 'Grup Daveti'),
                    ('group_join_request', 'Grup Katılım İsteği'),
                    ('group_join_approved', 'Grup Katılım Onaylandı'),
                    ('group_join_rejected', 'Grup Katılım Reddedildi'),
                    ('event_join_request', 'Etkinlik Katılım İsteği'),
                    ('event_join_approved', 'Etkinlik Katılım Onaylandı'),
                    ('event_join_rejected', 'Etkinlik Katılım Reddedildi'),
                    ('ride_request', 'Yolculuk Katılım İsteği'),
                    ('ride_update', 'Yolculuk Güncellemesi'),
                    ('group_update', 'Grup Güncellemesi'),
                    ('friend_request', 'Arkadaşlık İsteği'),
                    ('other', 'Diğer'),
                ],
                default='other',
                max_length=50,
                verbose_name='Bildirim Türü'
            ),
        ),
    ]
