# Generated by Django 5.2.4 on 2025-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_create_notification_preferences'),
        ('notifications', '0004_notification_types_update'),
    ]

    operations = [
    ]
