name: motoapp_frontend
description: MotoApp Flutter Frontend
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI & Tema
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.4.9
  rxdart: ^0.27.7

  # Network & API
  dio: ^5.3.3
  web_socket_channel: ^2.4.0
  retrofit: ^4.0.1
  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Harita ve Konum
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  http: ^1.2.1

  # Medya
  file_picker: ^10.2.1
  image_picker: ^1.0.4
  
  # URL Launcher
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  http_parser: ^4.0.2
  
  # Deep Link
  app_links: ^6.3.2
  
  # Supabase
  supabase_flutter: ^2.3.4
  
  # Firebase & Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  uuid: ^4.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/