name: motoapp_frontend
description: MotoApp Flutter Frontend
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI & Tema
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.4.9

  # Network & API
  dio: ^5.3.3
  web_socket_channel: ^3.0.3
  retrofit: ^4.0.1

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Harita ve Konum
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  http: ^1.2.1

  # Medya
  file_picker: ^10.2.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/