name: motoapp_frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter

  image_picker: ^0.8.7+5
  provider: ^6.1.5
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.13

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/spiride_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"   # Beyaz arka plan
  image: assets/images/spiride_logo.png  # Native splash logo (istersen kaldırabilirsin)
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFill