# Generated by Django 4.2.7

from django.db import migrations, models
import django.contrib.postgres.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('search_vector', models.TextField(blank=True)),
                ('group_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('group_description', models.TextField(blank=True)),
                ('group_search_vector', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_index',
            },
        ),
        migrations.RunSQL(
            "CREATE INDEX search_username_gin_idx ON search_index USING gin (username gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_username_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_first_name_gin_idx ON search_index USING gin (first_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_first_name_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_last_name_gin_idx ON search_index USING gin (last_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_last_name_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_full_name_gin_idx ON search_index USING gin (full_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_full_name_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_email_gin_idx ON search_index USING gin (email gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_email_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_group_name_gin_idx ON search_index USING gin (group_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_group_name_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_group_desc_gin_idx ON search_index USING gin (group_description gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_group_desc_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_vector_gin_idx ON search_index USING gin (search_vector gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_vector_gin_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX search_group_vector_gin_idx ON search_index USING gin (group_search_vector gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS search_group_vector_gin_idx;"
        ),
    ]
