# Generated by Django 5.2.4 on 2025-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_groupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Onay Gerekli'),
        ),
    ]
