# Generated by Django 5.2.4 on 2025-07-24 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj İçeriği")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Zaman Damgası"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu Bilgisi"),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_private_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alıcı",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_private_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel Mesaj",
                "verbose_name_plural": "Özel Mesajlar",
                "ordering": ["timestamp"],
            },
        ),
    ]
