# Generated by Django 5.2.4 on 2025-07-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Yolculuğun veya etkinliğin başlığı.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Yolculuk hakkında detaylı açıklama.', null=True)),
                ('start_location', models.CharField(help_text='Yolculuğun başlangıç noktası.', max_length=255)),
                ('end_location', models.CharField(help_text='Yolculuğun bitiş noktası.', max_length=255)),
                ('start_time', models.DateTimeField(help_text='Yolculuğun başlangıç tarihi ve saati.')),
                ('end_time', models.DateTimeField(blank=True, help_text='Yolculuğun tahmini bitiş tarihi ve saati (isteğe bağlı).', null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maksimum katılımcı sayısı (isteğe bağlı).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Yolculuğun hala aktif olup olmadığı.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Yolculuğu oluşturan kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Yolculuğa katılan kullanıcılar.', related_name='participating_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
