# Generated by Django 5.2.4 on 2025-07-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=10),
        ),
    ]
