# Generated by Django 5.2.4 on 2025-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_riderequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route_polyline',
            field=models.TextField(blank=True, help_text="Harita servisinden gelen kodlanmış rota polylines'ı (encoded polyline).", null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, help_text="Rota üzerindeki ara noktalar veya POI'lar JSON formatında.", null=True),
        ),
    ]
