# Generated by Django 5.2.4 on 2025-09-13 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('rides', '0004_ride_route_polyline_ride_waypoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Enlem')),
                ('longitude', models.FloatField(help_text='Boylam')),
                ('accuracy', models.FloatField(blank=True, help_text='Konum doğruluğu (metre)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Hız (km/h)', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Yön (derece)', null=True)),
                ('share_type', models.CharField(choices=[('ride', 'Yolculuk Sırasında'), ('group', 'Grup Üyeleri'), ('friends', 'Arkadaşlar'), ('public', 'Herkese Açık')], default='ride', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Paylaşım aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to='groups.group')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konum Paylaşımı',
                'verbose_name_plural': 'Konum Paylaşımları',
                'ordering': ['-created_at'],
            },
        ),
    ]
