# Generated by Django 5.2.4 on 2025-09-13 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_locationshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Şablon adı', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Açıklama')),
                ('category', models.CharField(choices=[('city', 'Şehir İçi'), ('highway', 'Otoyol'), ('mountain', 'Dağ'), ('coastal', 'Sahil'), ('historical', 'Tarihi'), ('nature', 'Doğa')], default='city', max_length=20)),
                ('route_polyline', models.TextField(help_text='Rota polylines')),
                ('waypoints', models.JSONField(default=list, help_text='Ara noktalar')),
                ('start_location', models.CharField(help_text='Başlangıç', max_length=255)),
                ('end_location', models.CharField(help_text='Bitiş', max_length=255)),
                ('distance_km', models.FloatField(help_text='Mesafe (km)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Tahmini süre (dakika)')),
                ('difficulty_level', models.PositiveIntegerField(default=1, help_text='Zorluk seviyesi (1-5)')),
                ('is_public', models.BooleanField(default=True, help_text='Herkese açık mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rota Şablonu',
                'verbose_name_plural': 'Rota Şablonları',
                'ordering': ['-created_at'],
            },
        ),
    ]
