# Generated by Django 5.2.4 on 2025-09-13 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('rides', '0007_routefavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='Başlangıç koordinatları [lat, lng]', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='end_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='Bitiş koordinatları [lat, lng]', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Yolculuğun tamamlanma tarihi.', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('casual', 'Günlük Sürüş'), ('touring', 'Tur Sürüşü'), ('group', 'Grup Sürüşü'), ('track', 'Pist Sürüşü'), ('adventure', 'Macera Sürüşü')], default='casual', help_text='Yolculuk türü.', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Herkese Açık'), ('friends', 'Sadece Arkadaşlar'), ('private', 'Özel')], default='public', help_text='Gizlilik seviyesi.', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Toplam mesafe (km).', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tahmini süre (dakika).', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Favori rota mı?'),
        ),
        migrations.AddField(
            model_name='ride',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Bağlı grup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_rides', to='groups.group'),
        ),
    ]
