# Generated by Django 5.2.4 on 2025-09-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_delete_mediafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
