// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek Web API key'i buraya yazın
    appId: '1:123456789:web:xxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek Web App ID'yi buraya yazın
    messagingSenderId: '123456789', // Firebase Console'dan gerçek Messaging Sender ID'yi buraya yazın
    projectId: 'motoapp-firebase', // Firebase Console'dan gerçek Project ID'yi buraya yazın
    authDomain: 'motoapp-firebase.firebaseapp.com', // Firebase Console'dan gerçek Auth Domain'i buraya yazın
    storageBucket: 'motoapp-firebase.appspot.com', // Firebase Console'dan gerçek Storage Bucket'ı buraya yazın
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek API key'i buraya yazın
    appId: '1:123456789:android:xxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek App ID'yi buraya yazın
    messagingSenderId: '123456789', // Firebase Console'dan gerçek Messaging Sender ID'yi buraya yazın
    projectId: 'motoapp-firebase', // Firebase Console'dan gerçek Project ID'yi buraya yazın
    storageBucket: 'motoapp-firebase.appspot.com', // Firebase Console'dan gerçek Storage Bucket'ı buraya yazın
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek iOS API key'i buraya yazın
    appId: '1:123456789:ios:xxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek iOS App ID'yi buraya yazın
    messagingSenderId: '123456789', // Firebase Console'dan gerçek Messaging Sender ID'yi buraya yazın
    projectId: 'motoapp-firebase', // Firebase Console'dan gerçek Project ID'yi buraya yazın
    storageBucket: 'motoapp-firebase.appspot.com', // Firebase Console'dan gerçek Storage Bucket'ı buraya yazın
    iosBundleId: 'com.example.frontend', // Gerçek iOS Bundle ID'yi buraya yazın
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek macOS API key'i buraya yazın
    appId: '1:123456789:ios:xxxxxxxxxxxxxxxxxxxxxxx', // Firebase Console'dan gerçek macOS App ID'yi buraya yazın
    messagingSenderId: '123456789', // Firebase Console'dan gerçek Messaging Sender ID'yi buraya yazın
    projectId: 'motoapp-firebase', // Firebase Console'dan gerçek Project ID'yi buraya yazın
    storageBucket: 'motoapp-firebase.appspot.com', // Firebase Console'dan gerçek Storage Bucket'ı buraya yazın
    iosBundleId: 'com.example.frontend', // Gerçek macOS Bundle ID'yi buraya yazın
  );
}
