# Generated by Django 5.2.4 on 2025-09-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımda'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='motorcycle_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motosiklet Modeli'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Profil Resmi URL'),
        ),
    ]
